# Generated by Django 4.0.4 on 2022-04-20 13:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Наименование группы')),
                ('amount', models.IntegerField(verbose_name='Число промо-кодов')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Промо-код')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='promo_codes.group', verbose_name='Наименование группы')),
            ],
        ),
    ]
